### ISSUE TITLE
Manipulating Data

### ISSUE THREAD

**Issue by phlco** [serkolch/citibike-viz#2]
Have you considered looking at lodash.js which provides a lot of ruby-esque methods that allow you to group and sort your data easier.

**Comment by phlco** [comment]
Have you looked into the fs module to "glob" or get all the files in a directory

**Comment by serkolch** [comment]
I looked at lodash & considered it, but ultimately I don't think it makes any of the data grouping easier.

I did incorporate glob though, so thanks for that heads up
